<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <PropertyGroup>
    <NoWarn>1591</NoWarn> <!-- Remove this to turn on warnings for missing XML Comments -->
    <NoWarn>NU1803</NoWarn> <!-- Remove this to turn on warnings for http nuget source -->
  </PropertyGroup>
</Project>